// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: controller.proto

package controller

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Controller_RegisterNode_FullMethodName            = "/kcore.controller.Controller/RegisterNode"
	Controller_Heartbeat_FullMethodName               = "/kcore.controller.Controller/Heartbeat"
	Controller_SyncVmState_FullMethodName             = "/kcore.controller.Controller/SyncVmState"
	Controller_SyncWorkloadState_FullMethodName       = "/kcore.controller.Controller/SyncWorkloadState"
	Controller_CreateVm_FullMethodName                = "/kcore.controller.Controller/CreateVm"
	Controller_UpdateVm_FullMethodName                = "/kcore.controller.Controller/UpdateVm"
	Controller_DeleteVm_FullMethodName                = "/kcore.controller.Controller/DeleteVm"
	Controller_SetVmDesiredState_FullMethodName       = "/kcore.controller.Controller/SetVmDesiredState"
	Controller_GetVm_FullMethodName                   = "/kcore.controller.Controller/GetVm"
	Controller_ListVms_FullMethodName                 = "/kcore.controller.Controller/ListVms"
	Controller_CreateWorkload_FullMethodName          = "/kcore.controller.Controller/CreateWorkload"
	Controller_DeleteWorkload_FullMethodName          = "/kcore.controller.Controller/DeleteWorkload"
	Controller_SetWorkloadDesiredState_FullMethodName = "/kcore.controller.Controller/SetWorkloadDesiredState"
	Controller_GetWorkload_FullMethodName             = "/kcore.controller.Controller/GetWorkload"
	Controller_ListWorkloads_FullMethodName           = "/kcore.controller.Controller/ListWorkloads"
	Controller_CreateNetwork_FullMethodName           = "/kcore.controller.Controller/CreateNetwork"
	Controller_DeleteNetwork_FullMethodName           = "/kcore.controller.Controller/DeleteNetwork"
	Controller_ListNetworks_FullMethodName            = "/kcore.controller.Controller/ListNetworks"
	Controller_CreateSecurityGroup_FullMethodName     = "/kcore.controller.Controller/CreateSecurityGroup"
	Controller_GetSecurityGroup_FullMethodName        = "/kcore.controller.Controller/GetSecurityGroup"
	Controller_ListSecurityGroups_FullMethodName      = "/kcore.controller.Controller/ListSecurityGroups"
	Controller_DeleteSecurityGroup_FullMethodName     = "/kcore.controller.Controller/DeleteSecurityGroup"
	Controller_AttachSecurityGroup_FullMethodName     = "/kcore.controller.Controller/AttachSecurityGroup"
	Controller_DetachSecurityGroup_FullMethodName     = "/kcore.controller.Controller/DetachSecurityGroup"
	Controller_ListNodes_FullMethodName               = "/kcore.controller.Controller/ListNodes"
	Controller_GetNode_FullMethodName                 = "/kcore.controller.Controller/GetNode"
	Controller_CreateSshKey_FullMethodName            = "/kcore.controller.Controller/CreateSshKey"
	Controller_DeleteSshKey_FullMethodName            = "/kcore.controller.Controller/DeleteSshKey"
	Controller_ListSshKeys_FullMethodName             = "/kcore.controller.Controller/ListSshKeys"
	Controller_GetSshKey_FullMethodName               = "/kcore.controller.Controller/GetSshKey"
	Controller_DrainNode_FullMethodName               = "/kcore.controller.Controller/DrainNode"
	Controller_ApproveNode_FullMethodName             = "/kcore.controller.Controller/ApproveNode"
	Controller_RejectNode_FullMethodName              = "/kcore.controller.Controller/RejectNode"
	Controller_RenewNodeCert_FullMethodName           = "/kcore.controller.Controller/RenewNodeCert"
	Controller_IssueNodeBootstrapCert_FullMethodName  = "/kcore.controller.Controller/IssueNodeBootstrapCert"
	Controller_RotateSubCa_FullMethodName             = "/kcore.controller.Controller/RotateSubCa"
	Controller_ReloadTls_FullMethodName               = "/kcore.controller.Controller/ReloadTls"
	Controller_GetComplianceReport_FullMethodName     = "/kcore.controller.Controller/GetComplianceReport"
	Controller_GetNetworkOverview_FullMethodName      = "/kcore.controller.Controller/GetNetworkOverview"
	Controller_GetStorageOverview_FullMethodName      = "/kcore.controller.Controller/GetStorageOverview"
	Controller_ListVolumes_FullMethodName             = "/kcore.controller.Controller/ListVolumes"
	Controller_CreateDiskLayout_FullMethodName        = "/kcore.controller.Controller/CreateDiskLayout"
	Controller_GetDiskLayout_FullMethodName           = "/kcore.controller.Controller/GetDiskLayout"
	Controller_ListDiskLayouts_FullMethodName         = "/kcore.controller.Controller/ListDiskLayouts"
	Controller_DeleteDiskLayout_FullMethodName        = "/kcore.controller.Controller/DeleteDiskLayout"
	Controller_ClassifyDiskLayout_FullMethodName      = "/kcore.controller.Controller/ClassifyDiskLayout"
)

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Controller service - orchestrates VMs across nodes
type ControllerClient interface {
	// Node registration and heartbeat
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	SyncVmState(ctx context.Context, in *SyncVmStateRequest, opts ...grpc.CallOption) (*SyncVmStateResponse, error)
	SyncWorkloadState(ctx context.Context, in *SyncWorkloadStateRequest, opts ...grpc.CallOption) (*SyncWorkloadStateResponse, error)
	// VM operations (declarative desired-state API managed by controller)
	CreateVm(ctx context.Context, in *CreateVmRequest, opts ...grpc.CallOption) (*CreateVmResponse, error)
	UpdateVm(ctx context.Context, in *UpdateVmRequest, opts ...grpc.CallOption) (*UpdateVmResponse, error)
	DeleteVm(ctx context.Context, in *DeleteVmRequest, opts ...grpc.CallOption) (*DeleteVmResponse, error)
	SetVmDesiredState(ctx context.Context, in *SetVmDesiredStateRequest, opts ...grpc.CallOption) (*SetVmDesiredStateResponse, error)
	GetVm(ctx context.Context, in *GetVmRequest, opts ...grpc.CallOption) (*GetVmResponse, error)
	ListVms(ctx context.Context, in *ListVmsRequest, opts ...grpc.CallOption) (*ListVmsResponse, error)
	CreateWorkload(ctx context.Context, in *CreateWorkloadRequest, opts ...grpc.CallOption) (*CreateWorkloadResponse, error)
	DeleteWorkload(ctx context.Context, in *DeleteWorkloadRequest, opts ...grpc.CallOption) (*DeleteWorkloadResponse, error)
	SetWorkloadDesiredState(ctx context.Context, in *SetWorkloadDesiredStateRequest, opts ...grpc.CallOption) (*SetWorkloadDesiredStateResponse, error)
	GetWorkload(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*GetWorkloadResponse, error)
	ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (*ListWorkloadsResponse, error)
	CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*CreateNetworkResponse, error)
	DeleteNetwork(ctx context.Context, in *DeleteNetworkRequest, opts ...grpc.CallOption) (*DeleteNetworkResponse, error)
	ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error)
	CreateSecurityGroup(ctx context.Context, in *CreateSecurityGroupRequest, opts ...grpc.CallOption) (*CreateSecurityGroupResponse, error)
	GetSecurityGroup(ctx context.Context, in *GetSecurityGroupRequest, opts ...grpc.CallOption) (*GetSecurityGroupResponse, error)
	ListSecurityGroups(ctx context.Context, in *ListSecurityGroupsRequest, opts ...grpc.CallOption) (*ListSecurityGroupsResponse, error)
	DeleteSecurityGroup(ctx context.Context, in *DeleteSecurityGroupRequest, opts ...grpc.CallOption) (*DeleteSecurityGroupResponse, error)
	AttachSecurityGroup(ctx context.Context, in *AttachSecurityGroupRequest, opts ...grpc.CallOption) (*AttachSecurityGroupResponse, error)
	DetachSecurityGroup(ctx context.Context, in *DetachSecurityGroupRequest, opts ...grpc.CallOption) (*DetachSecurityGroupResponse, error)
	// Node operations
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	// SSH key management
	CreateSshKey(ctx context.Context, in *CreateSshKeyRequest, opts ...grpc.CallOption) (*CreateSshKeyResponse, error)
	DeleteSshKey(ctx context.Context, in *DeleteSshKeyRequest, opts ...grpc.CallOption) (*DeleteSshKeyResponse, error)
	ListSshKeys(ctx context.Context, in *ListSshKeysRequest, opts ...grpc.CallOption) (*ListSshKeysResponse, error)
	GetSshKey(ctx context.Context, in *GetSshKeyRequest, opts ...grpc.CallOption) (*GetSshKeyResponse, error)
	// Node lifecycle
	DrainNode(ctx context.Context, in *DrainNodeRequest, opts ...grpc.CallOption) (*DrainNodeResponse, error)
	ApproveNode(ctx context.Context, in *ApproveNodeRequest, opts ...grpc.CallOption) (*ApproveNodeResponse, error)
	RejectNode(ctx context.Context, in *RejectNodeRequest, opts ...grpc.CallOption) (*RejectNodeResponse, error)
	// Certificate rotation
	RenewNodeCert(ctx context.Context, in *RenewNodeCertRequest, opts ...grpc.CallOption) (*RenewNodeCertResponse, error)
	// Bootstrap a node cert/key pair signed by controller sub-CA for fresh installs.
	IssueNodeBootstrapCert(ctx context.Context, in *IssueNodeBootstrapCertRequest, opts ...grpc.CallOption) (*IssueNodeBootstrapCertResponse, error)
	RotateSubCa(ctx context.Context, in *RotateSubCaRequest, opts ...grpc.CallOption) (*RotateSubCaResponse, error)
	ReloadTls(ctx context.Context, in *ReloadTlsRequest, opts ...grpc.CallOption) (*ReloadTlsResponse, error)
	// Compliance
	GetComplianceReport(ctx context.Context, in *GetComplianceReportRequest, opts ...grpc.CallOption) (*GetComplianceReportResponse, error)
	// Network overview: host interfaces from each node + default network config
	GetNetworkOverview(ctx context.Context, in *GetNetworkOverviewRequest, opts ...grpc.CallOption) (*GetNetworkOverviewResponse, error)
	// Storage overview: cluster-wide VM data-plane backends (filesystem / LVM / ZFS), LUKS stats,
	// and per-node block inventory from each node agent (lsblk).
	GetStorageOverview(ctx context.Context, in *GetStorageOverviewRequest, opts ...grpc.CallOption) (*GetStorageOverviewResponse, error)
	// Volume inventory: list all provisioned VM volumes across the cluster.
	ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error)
	// DiskLayout resource — per-node declarative disk layout. Implemented on the
	// node via disko; the operator surface uses the plain word "disk". Each
	// DiskLayout targets exactly one node; dangerous requests (those that would
	// touch a device currently backing an active workload) are refused by both
	// the controller pre-flight and the authoritative node-agent re-classifier.
	CreateDiskLayout(ctx context.Context, in *CreateDiskLayoutRequest, opts ...grpc.CallOption) (*CreateDiskLayoutResponse, error)
	GetDiskLayout(ctx context.Context, in *GetDiskLayoutRequest, opts ...grpc.CallOption) (*GetDiskLayoutResponse, error)
	ListDiskLayouts(ctx context.Context, in *ListDiskLayoutsRequest, opts ...grpc.CallOption) (*ListDiskLayoutsResponse, error)
	DeleteDiskLayout(ctx context.Context, in *DeleteDiskLayoutRequest, opts ...grpc.CallOption) (*DeleteDiskLayoutResponse, error)
	// Read-only pre-flight that runs the controller-side classifier without
	// persisting or dispatching to the node. Used by `kctl diff disklayout` so
	// operators can see SAFE/DANGEROUS before applying.
	ClassifyDiskLayout(ctx context.Context, in *ClassifyDiskLayoutRequest, opts ...grpc.CallOption) (*ClassifyDiskLayoutResponse, error)
}

type controllerClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerClient(cc grpc.ClientConnInterface) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, Controller_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, Controller_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) SyncVmState(ctx context.Context, in *SyncVmStateRequest, opts ...grpc.CallOption) (*SyncVmStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncVmStateResponse)
	err := c.cc.Invoke(ctx, Controller_SyncVmState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) SyncWorkloadState(ctx context.Context, in *SyncWorkloadStateRequest, opts ...grpc.CallOption) (*SyncWorkloadStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncWorkloadStateResponse)
	err := c.cc.Invoke(ctx, Controller_SyncWorkloadState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) CreateVm(ctx context.Context, in *CreateVmRequest, opts ...grpc.CallOption) (*CreateVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVmResponse)
	err := c.cc.Invoke(ctx, Controller_CreateVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) UpdateVm(ctx context.Context, in *UpdateVmRequest, opts ...grpc.CallOption) (*UpdateVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateVmResponse)
	err := c.cc.Invoke(ctx, Controller_UpdateVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) DeleteVm(ctx context.Context, in *DeleteVmRequest, opts ...grpc.CallOption) (*DeleteVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVmResponse)
	err := c.cc.Invoke(ctx, Controller_DeleteVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) SetVmDesiredState(ctx context.Context, in *SetVmDesiredStateRequest, opts ...grpc.CallOption) (*SetVmDesiredStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetVmDesiredStateResponse)
	err := c.cc.Invoke(ctx, Controller_SetVmDesiredState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetVm(ctx context.Context, in *GetVmRequest, opts ...grpc.CallOption) (*GetVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVmResponse)
	err := c.cc.Invoke(ctx, Controller_GetVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ListVms(ctx context.Context, in *ListVmsRequest, opts ...grpc.CallOption) (*ListVmsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVmsResponse)
	err := c.cc.Invoke(ctx, Controller_ListVms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) CreateWorkload(ctx context.Context, in *CreateWorkloadRequest, opts ...grpc.CallOption) (*CreateWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWorkloadResponse)
	err := c.cc.Invoke(ctx, Controller_CreateWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) DeleteWorkload(ctx context.Context, in *DeleteWorkloadRequest, opts ...grpc.CallOption) (*DeleteWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWorkloadResponse)
	err := c.cc.Invoke(ctx, Controller_DeleteWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) SetWorkloadDesiredState(ctx context.Context, in *SetWorkloadDesiredStateRequest, opts ...grpc.CallOption) (*SetWorkloadDesiredStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetWorkloadDesiredStateResponse)
	err := c.cc.Invoke(ctx, Controller_SetWorkloadDesiredState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetWorkload(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*GetWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkloadResponse)
	err := c.cc.Invoke(ctx, Controller_GetWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (*ListWorkloadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkloadsResponse)
	err := c.cc.Invoke(ctx, Controller_ListWorkloads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*CreateNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNetworkResponse)
	err := c.cc.Invoke(ctx, Controller_CreateNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) DeleteNetwork(ctx context.Context, in *DeleteNetworkRequest, opts ...grpc.CallOption) (*DeleteNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNetworkResponse)
	err := c.cc.Invoke(ctx, Controller_DeleteNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNetworksResponse)
	err := c.cc.Invoke(ctx, Controller_ListNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) CreateSecurityGroup(ctx context.Context, in *CreateSecurityGroupRequest, opts ...grpc.CallOption) (*CreateSecurityGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSecurityGroupResponse)
	err := c.cc.Invoke(ctx, Controller_CreateSecurityGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetSecurityGroup(ctx context.Context, in *GetSecurityGroupRequest, opts ...grpc.CallOption) (*GetSecurityGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecurityGroupResponse)
	err := c.cc.Invoke(ctx, Controller_GetSecurityGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ListSecurityGroups(ctx context.Context, in *ListSecurityGroupsRequest, opts ...grpc.CallOption) (*ListSecurityGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSecurityGroupsResponse)
	err := c.cc.Invoke(ctx, Controller_ListSecurityGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) DeleteSecurityGroup(ctx context.Context, in *DeleteSecurityGroupRequest, opts ...grpc.CallOption) (*DeleteSecurityGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSecurityGroupResponse)
	err := c.cc.Invoke(ctx, Controller_DeleteSecurityGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) AttachSecurityGroup(ctx context.Context, in *AttachSecurityGroupRequest, opts ...grpc.CallOption) (*AttachSecurityGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachSecurityGroupResponse)
	err := c.cc.Invoke(ctx, Controller_AttachSecurityGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) DetachSecurityGroup(ctx context.Context, in *DetachSecurityGroupRequest, opts ...grpc.CallOption) (*DetachSecurityGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetachSecurityGroupResponse)
	err := c.cc.Invoke(ctx, Controller_DetachSecurityGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, Controller_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, Controller_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) CreateSshKey(ctx context.Context, in *CreateSshKeyRequest, opts ...grpc.CallOption) (*CreateSshKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSshKeyResponse)
	err := c.cc.Invoke(ctx, Controller_CreateSshKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) DeleteSshKey(ctx context.Context, in *DeleteSshKeyRequest, opts ...grpc.CallOption) (*DeleteSshKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSshKeyResponse)
	err := c.cc.Invoke(ctx, Controller_DeleteSshKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ListSshKeys(ctx context.Context, in *ListSshKeysRequest, opts ...grpc.CallOption) (*ListSshKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSshKeysResponse)
	err := c.cc.Invoke(ctx, Controller_ListSshKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetSshKey(ctx context.Context, in *GetSshKeyRequest, opts ...grpc.CallOption) (*GetSshKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSshKeyResponse)
	err := c.cc.Invoke(ctx, Controller_GetSshKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) DrainNode(ctx context.Context, in *DrainNodeRequest, opts ...grpc.CallOption) (*DrainNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainNodeResponse)
	err := c.cc.Invoke(ctx, Controller_DrainNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ApproveNode(ctx context.Context, in *ApproveNodeRequest, opts ...grpc.CallOption) (*ApproveNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveNodeResponse)
	err := c.cc.Invoke(ctx, Controller_ApproveNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) RejectNode(ctx context.Context, in *RejectNodeRequest, opts ...grpc.CallOption) (*RejectNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectNodeResponse)
	err := c.cc.Invoke(ctx, Controller_RejectNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) RenewNodeCert(ctx context.Context, in *RenewNodeCertRequest, opts ...grpc.CallOption) (*RenewNodeCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewNodeCertResponse)
	err := c.cc.Invoke(ctx, Controller_RenewNodeCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) IssueNodeBootstrapCert(ctx context.Context, in *IssueNodeBootstrapCertRequest, opts ...grpc.CallOption) (*IssueNodeBootstrapCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueNodeBootstrapCertResponse)
	err := c.cc.Invoke(ctx, Controller_IssueNodeBootstrapCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) RotateSubCa(ctx context.Context, in *RotateSubCaRequest, opts ...grpc.CallOption) (*RotateSubCaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateSubCaResponse)
	err := c.cc.Invoke(ctx, Controller_RotateSubCa_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ReloadTls(ctx context.Context, in *ReloadTlsRequest, opts ...grpc.CallOption) (*ReloadTlsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadTlsResponse)
	err := c.cc.Invoke(ctx, Controller_ReloadTls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetComplianceReport(ctx context.Context, in *GetComplianceReportRequest, opts ...grpc.CallOption) (*GetComplianceReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetComplianceReportResponse)
	err := c.cc.Invoke(ctx, Controller_GetComplianceReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetNetworkOverview(ctx context.Context, in *GetNetworkOverviewRequest, opts ...grpc.CallOption) (*GetNetworkOverviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetworkOverviewResponse)
	err := c.cc.Invoke(ctx, Controller_GetNetworkOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetStorageOverview(ctx context.Context, in *GetStorageOverviewRequest, opts ...grpc.CallOption) (*GetStorageOverviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStorageOverviewResponse)
	err := c.cc.Invoke(ctx, Controller_GetStorageOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVolumesResponse)
	err := c.cc.Invoke(ctx, Controller_ListVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) CreateDiskLayout(ctx context.Context, in *CreateDiskLayoutRequest, opts ...grpc.CallOption) (*CreateDiskLayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDiskLayoutResponse)
	err := c.cc.Invoke(ctx, Controller_CreateDiskLayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetDiskLayout(ctx context.Context, in *GetDiskLayoutRequest, opts ...grpc.CallOption) (*GetDiskLayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiskLayoutResponse)
	err := c.cc.Invoke(ctx, Controller_GetDiskLayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ListDiskLayouts(ctx context.Context, in *ListDiskLayoutsRequest, opts ...grpc.CallOption) (*ListDiskLayoutsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDiskLayoutsResponse)
	err := c.cc.Invoke(ctx, Controller_ListDiskLayouts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) DeleteDiskLayout(ctx context.Context, in *DeleteDiskLayoutRequest, opts ...grpc.CallOption) (*DeleteDiskLayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDiskLayoutResponse)
	err := c.cc.Invoke(ctx, Controller_DeleteDiskLayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ClassifyDiskLayout(ctx context.Context, in *ClassifyDiskLayoutRequest, opts ...grpc.CallOption) (*ClassifyDiskLayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyDiskLayoutResponse)
	err := c.cc.Invoke(ctx, Controller_ClassifyDiskLayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
// All implementations must embed UnimplementedControllerServer
// for forward compatibility.
//
// Controller service - orchestrates VMs across nodes
type ControllerServer interface {
	// Node registration and heartbeat
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	SyncVmState(context.Context, *SyncVmStateRequest) (*SyncVmStateResponse, error)
	SyncWorkloadState(context.Context, *SyncWorkloadStateRequest) (*SyncWorkloadStateResponse, error)
	// VM operations (declarative desired-state API managed by controller)
	CreateVm(context.Context, *CreateVmRequest) (*CreateVmResponse, error)
	UpdateVm(context.Context, *UpdateVmRequest) (*UpdateVmResponse, error)
	DeleteVm(context.Context, *DeleteVmRequest) (*DeleteVmResponse, error)
	SetVmDesiredState(context.Context, *SetVmDesiredStateRequest) (*SetVmDesiredStateResponse, error)
	GetVm(context.Context, *GetVmRequest) (*GetVmResponse, error)
	ListVms(context.Context, *ListVmsRequest) (*ListVmsResponse, error)
	CreateWorkload(context.Context, *CreateWorkloadRequest) (*CreateWorkloadResponse, error)
	DeleteWorkload(context.Context, *DeleteWorkloadRequest) (*DeleteWorkloadResponse, error)
	SetWorkloadDesiredState(context.Context, *SetWorkloadDesiredStateRequest) (*SetWorkloadDesiredStateResponse, error)
	GetWorkload(context.Context, *GetWorkloadRequest) (*GetWorkloadResponse, error)
	ListWorkloads(context.Context, *ListWorkloadsRequest) (*ListWorkloadsResponse, error)
	CreateNetwork(context.Context, *CreateNetworkRequest) (*CreateNetworkResponse, error)
	DeleteNetwork(context.Context, *DeleteNetworkRequest) (*DeleteNetworkResponse, error)
	ListNetworks(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error)
	CreateSecurityGroup(context.Context, *CreateSecurityGroupRequest) (*CreateSecurityGroupResponse, error)
	GetSecurityGroup(context.Context, *GetSecurityGroupRequest) (*GetSecurityGroupResponse, error)
	ListSecurityGroups(context.Context, *ListSecurityGroupsRequest) (*ListSecurityGroupsResponse, error)
	DeleteSecurityGroup(context.Context, *DeleteSecurityGroupRequest) (*DeleteSecurityGroupResponse, error)
	AttachSecurityGroup(context.Context, *AttachSecurityGroupRequest) (*AttachSecurityGroupResponse, error)
	DetachSecurityGroup(context.Context, *DetachSecurityGroupRequest) (*DetachSecurityGroupResponse, error)
	// Node operations
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	// SSH key management
	CreateSshKey(context.Context, *CreateSshKeyRequest) (*CreateSshKeyResponse, error)
	DeleteSshKey(context.Context, *DeleteSshKeyRequest) (*DeleteSshKeyResponse, error)
	ListSshKeys(context.Context, *ListSshKeysRequest) (*ListSshKeysResponse, error)
	GetSshKey(context.Context, *GetSshKeyRequest) (*GetSshKeyResponse, error)
	// Node lifecycle
	DrainNode(context.Context, *DrainNodeRequest) (*DrainNodeResponse, error)
	ApproveNode(context.Context, *ApproveNodeRequest) (*ApproveNodeResponse, error)
	RejectNode(context.Context, *RejectNodeRequest) (*RejectNodeResponse, error)
	// Certificate rotation
	RenewNodeCert(context.Context, *RenewNodeCertRequest) (*RenewNodeCertResponse, error)
	// Bootstrap a node cert/key pair signed by controller sub-CA for fresh installs.
	IssueNodeBootstrapCert(context.Context, *IssueNodeBootstrapCertRequest) (*IssueNodeBootstrapCertResponse, error)
	RotateSubCa(context.Context, *RotateSubCaRequest) (*RotateSubCaResponse, error)
	ReloadTls(context.Context, *ReloadTlsRequest) (*ReloadTlsResponse, error)
	// Compliance
	GetComplianceReport(context.Context, *GetComplianceReportRequest) (*GetComplianceReportResponse, error)
	// Network overview: host interfaces from each node + default network config
	GetNetworkOverview(context.Context, *GetNetworkOverviewRequest) (*GetNetworkOverviewResponse, error)
	// Storage overview: cluster-wide VM data-plane backends (filesystem / LVM / ZFS), LUKS stats,
	// and per-node block inventory from each node agent (lsblk).
	GetStorageOverview(context.Context, *GetStorageOverviewRequest) (*GetStorageOverviewResponse, error)
	// Volume inventory: list all provisioned VM volumes across the cluster.
	ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error)
	// DiskLayout resource — per-node declarative disk layout. Implemented on the
	// node via disko; the operator surface uses the plain word "disk". Each
	// DiskLayout targets exactly one node; dangerous requests (those that would
	// touch a device currently backing an active workload) are refused by both
	// the controller pre-flight and the authoritative node-agent re-classifier.
	CreateDiskLayout(context.Context, *CreateDiskLayoutRequest) (*CreateDiskLayoutResponse, error)
	GetDiskLayout(context.Context, *GetDiskLayoutRequest) (*GetDiskLayoutResponse, error)
	ListDiskLayouts(context.Context, *ListDiskLayoutsRequest) (*ListDiskLayoutsResponse, error)
	DeleteDiskLayout(context.Context, *DeleteDiskLayoutRequest) (*DeleteDiskLayoutResponse, error)
	// Read-only pre-flight that runs the controller-side classifier without
	// persisting or dispatching to the node. Used by `kctl diff disklayout` so
	// operators can see SAFE/DANGEROUS before applying.
	ClassifyDiskLayout(context.Context, *ClassifyDiskLayoutRequest) (*ClassifyDiskLayoutResponse, error)
	mustEmbedUnimplementedControllerServer()
}

// UnimplementedControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerServer struct{}

func (UnimplementedControllerServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedControllerServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedControllerServer) SyncVmState(context.Context, *SyncVmStateRequest) (*SyncVmStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncVmState not implemented")
}
func (UnimplementedControllerServer) SyncWorkloadState(context.Context, *SyncWorkloadStateRequest) (*SyncWorkloadStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncWorkloadState not implemented")
}
func (UnimplementedControllerServer) CreateVm(context.Context, *CreateVmRequest) (*CreateVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVm not implemented")
}
func (UnimplementedControllerServer) UpdateVm(context.Context, *UpdateVmRequest) (*UpdateVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVm not implemented")
}
func (UnimplementedControllerServer) DeleteVm(context.Context, *DeleteVmRequest) (*DeleteVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVm not implemented")
}
func (UnimplementedControllerServer) SetVmDesiredState(context.Context, *SetVmDesiredStateRequest) (*SetVmDesiredStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetVmDesiredState not implemented")
}
func (UnimplementedControllerServer) GetVm(context.Context, *GetVmRequest) (*GetVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVm not implemented")
}
func (UnimplementedControllerServer) ListVms(context.Context, *ListVmsRequest) (*ListVmsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVms not implemented")
}
func (UnimplementedControllerServer) CreateWorkload(context.Context, *CreateWorkloadRequest) (*CreateWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkload not implemented")
}
func (UnimplementedControllerServer) DeleteWorkload(context.Context, *DeleteWorkloadRequest) (*DeleteWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWorkload not implemented")
}
func (UnimplementedControllerServer) SetWorkloadDesiredState(context.Context, *SetWorkloadDesiredStateRequest) (*SetWorkloadDesiredStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetWorkloadDesiredState not implemented")
}
func (UnimplementedControllerServer) GetWorkload(context.Context, *GetWorkloadRequest) (*GetWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkload not implemented")
}
func (UnimplementedControllerServer) ListWorkloads(context.Context, *ListWorkloadsRequest) (*ListWorkloadsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkloads not implemented")
}
func (UnimplementedControllerServer) CreateNetwork(context.Context, *CreateNetworkRequest) (*CreateNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNetwork not implemented")
}
func (UnimplementedControllerServer) DeleteNetwork(context.Context, *DeleteNetworkRequest) (*DeleteNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNetwork not implemented")
}
func (UnimplementedControllerServer) ListNetworks(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNetworks not implemented")
}
func (UnimplementedControllerServer) CreateSecurityGroup(context.Context, *CreateSecurityGroupRequest) (*CreateSecurityGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSecurityGroup not implemented")
}
func (UnimplementedControllerServer) GetSecurityGroup(context.Context, *GetSecurityGroupRequest) (*GetSecurityGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecurityGroup not implemented")
}
func (UnimplementedControllerServer) ListSecurityGroups(context.Context, *ListSecurityGroupsRequest) (*ListSecurityGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSecurityGroups not implemented")
}
func (UnimplementedControllerServer) DeleteSecurityGroup(context.Context, *DeleteSecurityGroupRequest) (*DeleteSecurityGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSecurityGroup not implemented")
}
func (UnimplementedControllerServer) AttachSecurityGroup(context.Context, *AttachSecurityGroupRequest) (*AttachSecurityGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachSecurityGroup not implemented")
}
func (UnimplementedControllerServer) DetachSecurityGroup(context.Context, *DetachSecurityGroupRequest) (*DetachSecurityGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachSecurityGroup not implemented")
}
func (UnimplementedControllerServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedControllerServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedControllerServer) CreateSshKey(context.Context, *CreateSshKeyRequest) (*CreateSshKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSshKey not implemented")
}
func (UnimplementedControllerServer) DeleteSshKey(context.Context, *DeleteSshKeyRequest) (*DeleteSshKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSshKey not implemented")
}
func (UnimplementedControllerServer) ListSshKeys(context.Context, *ListSshKeysRequest) (*ListSshKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSshKeys not implemented")
}
func (UnimplementedControllerServer) GetSshKey(context.Context, *GetSshKeyRequest) (*GetSshKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSshKey not implemented")
}
func (UnimplementedControllerServer) DrainNode(context.Context, *DrainNodeRequest) (*DrainNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DrainNode not implemented")
}
func (UnimplementedControllerServer) ApproveNode(context.Context, *ApproveNodeRequest) (*ApproveNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveNode not implemented")
}
func (UnimplementedControllerServer) RejectNode(context.Context, *RejectNodeRequest) (*RejectNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectNode not implemented")
}
func (UnimplementedControllerServer) RenewNodeCert(context.Context, *RenewNodeCertRequest) (*RenewNodeCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewNodeCert not implemented")
}
func (UnimplementedControllerServer) IssueNodeBootstrapCert(context.Context, *IssueNodeBootstrapCertRequest) (*IssueNodeBootstrapCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueNodeBootstrapCert not implemented")
}
func (UnimplementedControllerServer) RotateSubCa(context.Context, *RotateSubCaRequest) (*RotateSubCaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateSubCa not implemented")
}
func (UnimplementedControllerServer) ReloadTls(context.Context, *ReloadTlsRequest) (*ReloadTlsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadTls not implemented")
}
func (UnimplementedControllerServer) GetComplianceReport(context.Context, *GetComplianceReportRequest) (*GetComplianceReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetComplianceReport not implemented")
}
func (UnimplementedControllerServer) GetNetworkOverview(context.Context, *GetNetworkOverviewRequest) (*GetNetworkOverviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworkOverview not implemented")
}
func (UnimplementedControllerServer) GetStorageOverview(context.Context, *GetStorageOverviewRequest) (*GetStorageOverviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStorageOverview not implemented")
}
func (UnimplementedControllerServer) ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVolumes not implemented")
}
func (UnimplementedControllerServer) CreateDiskLayout(context.Context, *CreateDiskLayoutRequest) (*CreateDiskLayoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDiskLayout not implemented")
}
func (UnimplementedControllerServer) GetDiskLayout(context.Context, *GetDiskLayoutRequest) (*GetDiskLayoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiskLayout not implemented")
}
func (UnimplementedControllerServer) ListDiskLayouts(context.Context, *ListDiskLayoutsRequest) (*ListDiskLayoutsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDiskLayouts not implemented")
}
func (UnimplementedControllerServer) DeleteDiskLayout(context.Context, *DeleteDiskLayoutRequest) (*DeleteDiskLayoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDiskLayout not implemented")
}
func (UnimplementedControllerServer) ClassifyDiskLayout(context.Context, *ClassifyDiskLayoutRequest) (*ClassifyDiskLayoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClassifyDiskLayout not implemented")
}
func (UnimplementedControllerServer) mustEmbedUnimplementedControllerServer() {}
func (UnimplementedControllerServer) testEmbeddedByValue()                    {}

// UnsafeControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServer will
// result in compilation errors.
type UnsafeControllerServer interface {
	mustEmbedUnimplementedControllerServer()
}

func RegisterControllerServer(s grpc.ServiceRegistrar, srv ControllerServer) {
	// If the following call panics, it indicates UnimplementedControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Controller_ServiceDesc, srv)
}

func _Controller_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_SyncVmState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncVmStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).SyncVmState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_SyncVmState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).SyncVmState(ctx, req.(*SyncVmStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_SyncWorkloadState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncWorkloadStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).SyncWorkloadState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_SyncWorkloadState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).SyncWorkloadState(ctx, req.(*SyncWorkloadStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_CreateVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).CreateVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_CreateVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).CreateVm(ctx, req.(*CreateVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_UpdateVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).UpdateVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_UpdateVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).UpdateVm(ctx, req.(*UpdateVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_DeleteVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).DeleteVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_DeleteVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).DeleteVm(ctx, req.(*DeleteVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_SetVmDesiredState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVmDesiredStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).SetVmDesiredState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_SetVmDesiredState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).SetVmDesiredState(ctx, req.(*SetVmDesiredStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_GetVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetVm(ctx, req.(*GetVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ListVms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ListVms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_ListVms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ListVms(ctx, req.(*ListVmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_CreateWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).CreateWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_CreateWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).CreateWorkload(ctx, req.(*CreateWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_DeleteWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).DeleteWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_DeleteWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).DeleteWorkload(ctx, req.(*DeleteWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_SetWorkloadDesiredState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetWorkloadDesiredStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).SetWorkloadDesiredState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_SetWorkloadDesiredState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).SetWorkloadDesiredState(ctx, req.(*SetWorkloadDesiredStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_GetWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetWorkload(ctx, req.(*GetWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ListWorkloads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkloadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ListWorkloads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_ListWorkloads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ListWorkloads(ctx, req.(*ListWorkloadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_CreateNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).CreateNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_CreateNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).CreateNetwork(ctx, req.(*CreateNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_DeleteNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).DeleteNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_DeleteNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).DeleteNetwork(ctx, req.(*DeleteNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ListNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ListNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_ListNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ListNetworks(ctx, req.(*ListNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_CreateSecurityGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSecurityGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).CreateSecurityGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_CreateSecurityGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).CreateSecurityGroup(ctx, req.(*CreateSecurityGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetSecurityGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecurityGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetSecurityGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_GetSecurityGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetSecurityGroup(ctx, req.(*GetSecurityGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ListSecurityGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecurityGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ListSecurityGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_ListSecurityGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ListSecurityGroups(ctx, req.(*ListSecurityGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_DeleteSecurityGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSecurityGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).DeleteSecurityGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_DeleteSecurityGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).DeleteSecurityGroup(ctx, req.(*DeleteSecurityGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_AttachSecurityGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachSecurityGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).AttachSecurityGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_AttachSecurityGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).AttachSecurityGroup(ctx, req.(*AttachSecurityGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_DetachSecurityGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachSecurityGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).DetachSecurityGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_DetachSecurityGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).DetachSecurityGroup(ctx, req.(*DetachSecurityGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_CreateSshKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSshKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).CreateSshKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_CreateSshKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).CreateSshKey(ctx, req.(*CreateSshKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_DeleteSshKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSshKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).DeleteSshKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_DeleteSshKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).DeleteSshKey(ctx, req.(*DeleteSshKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ListSshKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSshKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ListSshKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_ListSshKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ListSshKeys(ctx, req.(*ListSshKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetSshKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSshKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetSshKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_GetSshKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetSshKey(ctx, req.(*GetSshKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_DrainNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).DrainNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_DrainNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).DrainNode(ctx, req.(*DrainNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ApproveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ApproveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_ApproveNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ApproveNode(ctx, req.(*ApproveNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_RejectNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).RejectNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_RejectNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).RejectNode(ctx, req.(*RejectNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_RenewNodeCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewNodeCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).RenewNodeCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_RenewNodeCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).RenewNodeCert(ctx, req.(*RenewNodeCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_IssueNodeBootstrapCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueNodeBootstrapCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).IssueNodeBootstrapCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_IssueNodeBootstrapCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).IssueNodeBootstrapCert(ctx, req.(*IssueNodeBootstrapCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_RotateSubCa_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateSubCaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).RotateSubCa(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_RotateSubCa_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).RotateSubCa(ctx, req.(*RotateSubCaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ReloadTls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadTlsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ReloadTls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_ReloadTls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ReloadTls(ctx, req.(*ReloadTlsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetComplianceReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComplianceReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetComplianceReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_GetComplianceReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetComplianceReport(ctx, req.(*GetComplianceReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetNetworkOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetNetworkOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_GetNetworkOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetNetworkOverview(ctx, req.(*GetNetworkOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetStorageOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorageOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetStorageOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_GetStorageOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetStorageOverview(ctx, req.(*GetStorageOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ListVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ListVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_ListVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ListVolumes(ctx, req.(*ListVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_CreateDiskLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDiskLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).CreateDiskLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_CreateDiskLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).CreateDiskLayout(ctx, req.(*CreateDiskLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetDiskLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiskLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetDiskLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_GetDiskLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetDiskLayout(ctx, req.(*GetDiskLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ListDiskLayouts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDiskLayoutsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ListDiskLayouts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_ListDiskLayouts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ListDiskLayouts(ctx, req.(*ListDiskLayoutsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_DeleteDiskLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDiskLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).DeleteDiskLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_DeleteDiskLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).DeleteDiskLayout(ctx, req.(*DeleteDiskLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ClassifyDiskLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyDiskLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ClassifyDiskLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_ClassifyDiskLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ClassifyDiskLayout(ctx, req.(*ClassifyDiskLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Controller_ServiceDesc is the grpc.ServiceDesc for Controller service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Controller_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kcore.controller.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _Controller_RegisterNode_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Controller_Heartbeat_Handler,
		},
		{
			MethodName: "SyncVmState",
			Handler:    _Controller_SyncVmState_Handler,
		},
		{
			MethodName: "SyncWorkloadState",
			Handler:    _Controller_SyncWorkloadState_Handler,
		},
		{
			MethodName: "CreateVm",
			Handler:    _Controller_CreateVm_Handler,
		},
		{
			MethodName: "UpdateVm",
			Handler:    _Controller_UpdateVm_Handler,
		},
		{
			MethodName: "DeleteVm",
			Handler:    _Controller_DeleteVm_Handler,
		},
		{
			MethodName: "SetVmDesiredState",
			Handler:    _Controller_SetVmDesiredState_Handler,
		},
		{
			MethodName: "GetVm",
			Handler:    _Controller_GetVm_Handler,
		},
		{
			MethodName: "ListVms",
			Handler:    _Controller_ListVms_Handler,
		},
		{
			MethodName: "CreateWorkload",
			Handler:    _Controller_CreateWorkload_Handler,
		},
		{
			MethodName: "DeleteWorkload",
			Handler:    _Controller_DeleteWorkload_Handler,
		},
		{
			MethodName: "SetWorkloadDesiredState",
			Handler:    _Controller_SetWorkloadDesiredState_Handler,
		},
		{
			MethodName: "GetWorkload",
			Handler:    _Controller_GetWorkload_Handler,
		},
		{
			MethodName: "ListWorkloads",
			Handler:    _Controller_ListWorkloads_Handler,
		},
		{
			MethodName: "CreateNetwork",
			Handler:    _Controller_CreateNetwork_Handler,
		},
		{
			MethodName: "DeleteNetwork",
			Handler:    _Controller_DeleteNetwork_Handler,
		},
		{
			MethodName: "ListNetworks",
			Handler:    _Controller_ListNetworks_Handler,
		},
		{
			MethodName: "CreateSecurityGroup",
			Handler:    _Controller_CreateSecurityGroup_Handler,
		},
		{
			MethodName: "GetSecurityGroup",
			Handler:    _Controller_GetSecurityGroup_Handler,
		},
		{
			MethodName: "ListSecurityGroups",
			Handler:    _Controller_ListSecurityGroups_Handler,
		},
		{
			MethodName: "DeleteSecurityGroup",
			Handler:    _Controller_DeleteSecurityGroup_Handler,
		},
		{
			MethodName: "AttachSecurityGroup",
			Handler:    _Controller_AttachSecurityGroup_Handler,
		},
		{
			MethodName: "DetachSecurityGroup",
			Handler:    _Controller_DetachSecurityGroup_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _Controller_ListNodes_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _Controller_GetNode_Handler,
		},
		{
			MethodName: "CreateSshKey",
			Handler:    _Controller_CreateSshKey_Handler,
		},
		{
			MethodName: "DeleteSshKey",
			Handler:    _Controller_DeleteSshKey_Handler,
		},
		{
			MethodName: "ListSshKeys",
			Handler:    _Controller_ListSshKeys_Handler,
		},
		{
			MethodName: "GetSshKey",
			Handler:    _Controller_GetSshKey_Handler,
		},
		{
			MethodName: "DrainNode",
			Handler:    _Controller_DrainNode_Handler,
		},
		{
			MethodName: "ApproveNode",
			Handler:    _Controller_ApproveNode_Handler,
		},
		{
			MethodName: "RejectNode",
			Handler:    _Controller_RejectNode_Handler,
		},
		{
			MethodName: "RenewNodeCert",
			Handler:    _Controller_RenewNodeCert_Handler,
		},
		{
			MethodName: "IssueNodeBootstrapCert",
			Handler:    _Controller_IssueNodeBootstrapCert_Handler,
		},
		{
			MethodName: "RotateSubCa",
			Handler:    _Controller_RotateSubCa_Handler,
		},
		{
			MethodName: "ReloadTls",
			Handler:    _Controller_ReloadTls_Handler,
		},
		{
			MethodName: "GetComplianceReport",
			Handler:    _Controller_GetComplianceReport_Handler,
		},
		{
			MethodName: "GetNetworkOverview",
			Handler:    _Controller_GetNetworkOverview_Handler,
		},
		{
			MethodName: "GetStorageOverview",
			Handler:    _Controller_GetStorageOverview_Handler,
		},
		{
			MethodName: "ListVolumes",
			Handler:    _Controller_ListVolumes_Handler,
		},
		{
			MethodName: "CreateDiskLayout",
			Handler:    _Controller_CreateDiskLayout_Handler,
		},
		{
			MethodName: "GetDiskLayout",
			Handler:    _Controller_GetDiskLayout_Handler,
		},
		{
			MethodName: "ListDiskLayouts",
			Handler:    _Controller_ListDiskLayouts_Handler,
		},
		{
			MethodName: "DeleteDiskLayout",
			Handler:    _Controller_DeleteDiskLayout_Handler,
		},
		{
			MethodName: "ClassifyDiskLayout",
			Handler:    _Controller_ClassifyDiskLayout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller.proto",
}

const (
	ControllerAdmin_ApplyNixConfig_FullMethodName             = "/kcore.controller.ControllerAdmin/ApplyNixConfig"
	ControllerAdmin_GetReplicationEvents_FullMethodName       = "/kcore.controller.ControllerAdmin/GetReplicationEvents"
	ControllerAdmin_AckReplicationEvents_FullMethodName       = "/kcore.controller.ControllerAdmin/AckReplicationEvents"
	ControllerAdmin_GetReplicationStatus_FullMethodName       = "/kcore.controller.ControllerAdmin/GetReplicationStatus"
	ControllerAdmin_ListReplicationConflicts_FullMethodName   = "/kcore.controller.ControllerAdmin/ListReplicationConflicts"
	ControllerAdmin_ResolveReplicationConflict_FullMethodName = "/kcore.controller.ControllerAdmin/ResolveReplicationConflict"
)

// ControllerAdminClient is the client API for ControllerAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControllerAdmin service provides controller-level management operations.
// Deployments are expected to enforce mTLS on the transport layer.
type ControllerAdminClient interface {
	// ApplyNixConfig replaces the controller's /etc/nixos/configuration.nix with
	// the provided content and (optionally) triggers a nixos-rebuild.
	ApplyNixConfig(ctx context.Context, in *ApplyNixConfigRequest, opts ...grpc.CallOption) (*ApplyNixConfigResponse, error)
	// Returns a page of replication outbox events after the provided cursor.
	GetReplicationEvents(ctx context.Context, in *GetReplicationEventsRequest, opts ...grpc.CallOption) (*GetReplicationEventsResponse, error)
	// Stores peer replication acknowledgement frontier.
	AckReplicationEvents(ctx context.Context, in *AckReplicationEventsRequest, opts ...grpc.CallOption) (*AckReplicationEventsResponse, error)
	// Reports replication lag and frontier health.
	GetReplicationStatus(ctx context.Context, in *GetReplicationStatusRequest, opts ...grpc.CallOption) (*GetReplicationStatusResponse, error)
	// Lists unresolved replication conflicts for operator workflows.
	ListReplicationConflicts(ctx context.Context, in *ListReplicationConflictsRequest, opts ...grpc.CallOption) (*ListReplicationConflictsResponse, error)
	// Marks a replication conflict resolved.
	ResolveReplicationConflict(ctx context.Context, in *ResolveReplicationConflictRequest, opts ...grpc.CallOption) (*ResolveReplicationConflictResponse, error)
}

type controllerAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerAdminClient(cc grpc.ClientConnInterface) ControllerAdminClient {
	return &controllerAdminClient{cc}
}

func (c *controllerAdminClient) ApplyNixConfig(ctx context.Context, in *ApplyNixConfigRequest, opts ...grpc.CallOption) (*ApplyNixConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyNixConfigResponse)
	err := c.cc.Invoke(ctx, ControllerAdmin_ApplyNixConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerAdminClient) GetReplicationEvents(ctx context.Context, in *GetReplicationEventsRequest, opts ...grpc.CallOption) (*GetReplicationEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReplicationEventsResponse)
	err := c.cc.Invoke(ctx, ControllerAdmin_GetReplicationEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerAdminClient) AckReplicationEvents(ctx context.Context, in *AckReplicationEventsRequest, opts ...grpc.CallOption) (*AckReplicationEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckReplicationEventsResponse)
	err := c.cc.Invoke(ctx, ControllerAdmin_AckReplicationEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerAdminClient) GetReplicationStatus(ctx context.Context, in *GetReplicationStatusRequest, opts ...grpc.CallOption) (*GetReplicationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReplicationStatusResponse)
	err := c.cc.Invoke(ctx, ControllerAdmin_GetReplicationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerAdminClient) ListReplicationConflicts(ctx context.Context, in *ListReplicationConflictsRequest, opts ...grpc.CallOption) (*ListReplicationConflictsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReplicationConflictsResponse)
	err := c.cc.Invoke(ctx, ControllerAdmin_ListReplicationConflicts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerAdminClient) ResolveReplicationConflict(ctx context.Context, in *ResolveReplicationConflictRequest, opts ...grpc.CallOption) (*ResolveReplicationConflictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveReplicationConflictResponse)
	err := c.cc.Invoke(ctx, ControllerAdmin_ResolveReplicationConflict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerAdminServer is the server API for ControllerAdmin service.
// All implementations must embed UnimplementedControllerAdminServer
// for forward compatibility.
//
// ControllerAdmin service provides controller-level management operations.
// Deployments are expected to enforce mTLS on the transport layer.
type ControllerAdminServer interface {
	// ApplyNixConfig replaces the controller's /etc/nixos/configuration.nix with
	// the provided content and (optionally) triggers a nixos-rebuild.
	ApplyNixConfig(context.Context, *ApplyNixConfigRequest) (*ApplyNixConfigResponse, error)
	// Returns a page of replication outbox events after the provided cursor.
	GetReplicationEvents(context.Context, *GetReplicationEventsRequest) (*GetReplicationEventsResponse, error)
	// Stores peer replication acknowledgement frontier.
	AckReplicationEvents(context.Context, *AckReplicationEventsRequest) (*AckReplicationEventsResponse, error)
	// Reports replication lag and frontier health.
	GetReplicationStatus(context.Context, *GetReplicationStatusRequest) (*GetReplicationStatusResponse, error)
	// Lists unresolved replication conflicts for operator workflows.
	ListReplicationConflicts(context.Context, *ListReplicationConflictsRequest) (*ListReplicationConflictsResponse, error)
	// Marks a replication conflict resolved.
	ResolveReplicationConflict(context.Context, *ResolveReplicationConflictRequest) (*ResolveReplicationConflictResponse, error)
	mustEmbedUnimplementedControllerAdminServer()
}

// UnimplementedControllerAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerAdminServer struct{}

func (UnimplementedControllerAdminServer) ApplyNixConfig(context.Context, *ApplyNixConfigRequest) (*ApplyNixConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyNixConfig not implemented")
}
func (UnimplementedControllerAdminServer) GetReplicationEvents(context.Context, *GetReplicationEventsRequest) (*GetReplicationEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReplicationEvents not implemented")
}
func (UnimplementedControllerAdminServer) AckReplicationEvents(context.Context, *AckReplicationEventsRequest) (*AckReplicationEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckReplicationEvents not implemented")
}
func (UnimplementedControllerAdminServer) GetReplicationStatus(context.Context, *GetReplicationStatusRequest) (*GetReplicationStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReplicationStatus not implemented")
}
func (UnimplementedControllerAdminServer) ListReplicationConflicts(context.Context, *ListReplicationConflictsRequest) (*ListReplicationConflictsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReplicationConflicts not implemented")
}
func (UnimplementedControllerAdminServer) ResolveReplicationConflict(context.Context, *ResolveReplicationConflictRequest) (*ResolveReplicationConflictResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveReplicationConflict not implemented")
}
func (UnimplementedControllerAdminServer) mustEmbedUnimplementedControllerAdminServer() {}
func (UnimplementedControllerAdminServer) testEmbeddedByValue()                         {}

// UnsafeControllerAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerAdminServer will
// result in compilation errors.
type UnsafeControllerAdminServer interface {
	mustEmbedUnimplementedControllerAdminServer()
}

func RegisterControllerAdminServer(s grpc.ServiceRegistrar, srv ControllerAdminServer) {
	// If the following call panics, it indicates UnimplementedControllerAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControllerAdmin_ServiceDesc, srv)
}

func _ControllerAdmin_ApplyNixConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyNixConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerAdminServer).ApplyNixConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerAdmin_ApplyNixConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerAdminServer).ApplyNixConfig(ctx, req.(*ApplyNixConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerAdmin_GetReplicationEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReplicationEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerAdminServer).GetReplicationEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerAdmin_GetReplicationEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerAdminServer).GetReplicationEvents(ctx, req.(*GetReplicationEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerAdmin_AckReplicationEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckReplicationEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerAdminServer).AckReplicationEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerAdmin_AckReplicationEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerAdminServer).AckReplicationEvents(ctx, req.(*AckReplicationEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerAdmin_GetReplicationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReplicationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerAdminServer).GetReplicationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerAdmin_GetReplicationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerAdminServer).GetReplicationStatus(ctx, req.(*GetReplicationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerAdmin_ListReplicationConflicts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReplicationConflictsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerAdminServer).ListReplicationConflicts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerAdmin_ListReplicationConflicts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerAdminServer).ListReplicationConflicts(ctx, req.(*ListReplicationConflictsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerAdmin_ResolveReplicationConflict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveReplicationConflictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerAdminServer).ResolveReplicationConflict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerAdmin_ResolveReplicationConflict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerAdminServer).ResolveReplicationConflict(ctx, req.(*ResolveReplicationConflictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControllerAdmin_ServiceDesc is the grpc.ServiceDesc for ControllerAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControllerAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kcore.controller.ControllerAdmin",
	HandlerType: (*ControllerAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyNixConfig",
			Handler:    _ControllerAdmin_ApplyNixConfig_Handler,
		},
		{
			MethodName: "GetReplicationEvents",
			Handler:    _ControllerAdmin_GetReplicationEvents_Handler,
		},
		{
			MethodName: "AckReplicationEvents",
			Handler:    _ControllerAdmin_AckReplicationEvents_Handler,
		},
		{
			MethodName: "GetReplicationStatus",
			Handler:    _ControllerAdmin_GetReplicationStatus_Handler,
		},
		{
			MethodName: "ListReplicationConflicts",
			Handler:    _ControllerAdmin_ListReplicationConflicts_Handler,
		},
		{
			MethodName: "ResolveReplicationConflict",
			Handler:    _ControllerAdmin_ResolveReplicationConflict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller.proto",
}
