// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: node_admin.proto

package node

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageBackendType int32

const (
	StorageBackendType_STORAGE_BACKEND_TYPE_UNSPECIFIED StorageBackendType = 0
	StorageBackendType_STORAGE_BACKEND_TYPE_FILESYSTEM  StorageBackendType = 1
	StorageBackendType_STORAGE_BACKEND_TYPE_LVM         StorageBackendType = 2
	StorageBackendType_STORAGE_BACKEND_TYPE_ZFS         StorageBackendType = 3
	StorageBackendType_STORAGE_BACKEND_TYPE_CEPH        StorageBackendType = 4
)

// Enum value maps for StorageBackendType.
var (
	StorageBackendType_name = map[int32]string{
		0: "STORAGE_BACKEND_TYPE_UNSPECIFIED",
		1: "STORAGE_BACKEND_TYPE_FILESYSTEM",
		2: "STORAGE_BACKEND_TYPE_LVM",
		3: "STORAGE_BACKEND_TYPE_ZFS",
		4: "STORAGE_BACKEND_TYPE_CEPH",
	}
	StorageBackendType_value = map[string]int32{
		"STORAGE_BACKEND_TYPE_UNSPECIFIED": 0,
		"STORAGE_BACKEND_TYPE_FILESYSTEM":  1,
		"STORAGE_BACKEND_TYPE_LVM":         2,
		"STORAGE_BACKEND_TYPE_ZFS":         3,
		"STORAGE_BACKEND_TYPE_CEPH":        4,
	}
)

func (x StorageBackendType) Enum() *StorageBackendType {
	p := new(StorageBackendType)
	*p = x
	return p
}

func (x StorageBackendType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageBackendType) Descriptor() protoreflect.EnumDescriptor {
	return file_node_admin_proto_enumTypes[0].Descriptor()
}

func (StorageBackendType) Type() protoreflect.EnumType {
	return &file_node_admin_proto_enumTypes[0]
}

func (x StorageBackendType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageBackendType.Descriptor instead.
func (StorageBackendType) EnumDescriptor() ([]byte, []int) {
	return file_node_admin_proto_rawDescGZIP(), []int{0}
}

type InstallToDiskRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OsDisk            string                 `protobuf:"bytes,1,opt,name=os_disk,json=osDisk,proto3" json:"os_disk,omitempty"`
	DataDisks         []string               `protobuf:"bytes,2,rep,name=data_disks,json=dataDisks,proto3" json:"data_disks,omitempty"`
	Controller        string                 `protobuf:"bytes,3,opt,name=controller,proto3" json:"controller,omitempty"`
	CaCertPem         string                 `protobuf:"bytes,4,opt,name=ca_cert_pem,json=caCertPem,proto3" json:"ca_cert_pem,omitempty"`
	NodeCertPem       string                 `protobuf:"bytes,5,opt,name=node_cert_pem,json=nodeCertPem,proto3" json:"node_cert_pem,omitempty"`
	NodeKeyPem        string                 `protobuf:"bytes,6,opt,name=node_key_pem,json=nodeKeyPem,proto3" json:"node_key_pem,omitempty"`
	ControllerCertPem string                 `protobuf:"bytes,7,opt,name=controller_cert_pem,json=controllerCertPem,proto3" json:"controller_cert_pem,omitempty"`
	ControllerKeyPem  string                 `protobuf:"bytes,8,opt,name=controller_key_pem,json=controllerKeyPem,proto3" json:"controller_key_pem,omitempty"`
	KctlCertPem       string                 `protobuf:"bytes,9,opt,name=kctl_cert_pem,json=kctlCertPem,proto3" json:"kctl_cert_pem,omitempty"`
	KctlKeyPem        string                 `protobuf:"bytes,10,opt,name=kctl_key_pem,json=kctlKeyPem,proto3" json:"kctl_key_pem,omitempty"`
	RunController     bool                   `protobuf:"varint,11,opt,name=run_controller,json=runController,proto3" json:"run_controller,omitempty"`
	DataDiskMode      string                 `protobuf:"bytes,12,opt,name=data_disk_mode,json=dataDiskMode,proto3" json:"data_disk_mode,omitempty"`
	StorageBackend    StorageBackendType     `protobuf:"varint,13,opt,name=storage_backend,json=storageBackend,proto3,enum=kcore.node.StorageBackendType" json:"storage_backend,omitempty"`
	LvmVgName         string                 `protobuf:"bytes,14,opt,name=lvm_vg_name,json=lvmVgName,proto3" json:"lvm_vg_name,omitempty"`
	LvmLvPrefix       string                 `protobuf:"bytes,15,opt,name=lvm_lv_prefix,json=lvmLvPrefix,proto3" json:"lvm_lv_prefix,omitempty"`
	ZfsPoolName       string                 `protobuf:"bytes,16,opt,name=zfs_pool_name,json=zfsPoolName,proto3" json:"zfs_pool_name,omitempty"`
	ZfsDatasetPrefix  string                 `protobuf:"bytes,17,opt,name=zfs_dataset_prefix,json=zfsDatasetPrefix,proto3" json:"zfs_dataset_prefix,omitempty"`
	DisableVxlan      bool                   `protobuf:"varint,18,opt,name=disable_vxlan,json=disableVxlan,proto3" json:"disable_vxlan,omitempty"`
	SubCaCertPem      string                 `protobuf:"bytes,19,opt,name=sub_ca_cert_pem,json=subCaCertPem,proto3" json:"sub_ca_cert_pem,omitempty"`
	SubCaKeyPem       string                 `protobuf:"bytes,20,opt,name=sub_ca_key_pem,json=subCaKeyPem,proto3" json:"sub_ca_key_pem,omitempty"`
	DcId              string                 `protobuf:"bytes,21,opt,name=dc_id,json=dcId,proto3" json:"dc_id,omitempty"`
	Controllers       []string               `protobuf:"bytes,22,rep,name=controllers,proto3" json:"controllers,omitempty"`
	Hostname          string                 `protobuf:"bytes,23,opt,name=hostname,proto3" json:"hostname,omitempty"`
	NodeId            string                 `protobuf:"bytes,24,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InstallToDiskRequest) Reset() {
	*x = InstallToDiskRequest{}
	mi := &file_node_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallToDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallToDiskRequest) ProtoMessage() {}

func (x *InstallToDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallToDiskRequest.ProtoReflect.Descriptor instead.
func (*InstallToDiskRequest) Descriptor() ([]byte, []int) {
	return file_node_admin_proto_rawDescGZIP(), []int{0}
}

func (x *InstallToDiskRequest) GetOsDisk() string {
	if x != nil {
		return x.OsDisk
	}
	return ""
}

func (x *InstallToDiskRequest) GetDataDisks() []string {
	if x != nil {
		return x.DataDisks
	}
	return nil
}

func (x *InstallToDiskRequest) GetController() string {
	if x != nil {
		return x.Controller
	}
	return ""
}

func (x *InstallToDiskRequest) GetCaCertPem() string {
	if x != nil {
		return x.CaCertPem
	}
	return ""
}

func (x *InstallToDiskRequest) GetNodeCertPem() string {
	if x != nil {
		return x.NodeCertPem
	}
	return ""
}

func (x *InstallToDiskRequest) GetNodeKeyPem() string {
	if x != nil {
		return x.NodeKeyPem
	}
	return ""
}

func (x *InstallToDiskRequest) GetControllerCertPem() string {
	if x != nil {
		return x.ControllerCertPem
	}
	return ""
}

func (x *InstallToDiskRequest) GetControllerKeyPem() string {
	if x != nil {
		return x.ControllerKeyPem
	}
	return ""
}

func (x *InstallToDiskRequest) GetKctlCertPem() string {
	if x != nil {
		return x.KctlCertPem
	}
	return ""
}

func (x *InstallToDiskRequest) GetKctlKeyPem() string {
	if x != nil {
		return x.KctlKeyPem
	}
	return ""
}

func (x *InstallToDiskRequest) GetRunController() bool {
	if x != nil {
		return x.RunController
	}
	return false
}

func (x *InstallToDiskRequest) GetDataDiskMode() string {
	if x != nil {
		return x.DataDiskMode
	}
	return ""
}

func (x *InstallToDiskRequest) GetStorageBackend() StorageBackendType {
	if x != nil {
		return x.StorageBackend
	}
	return StorageBackendType_STORAGE_BACKEND_TYPE_UNSPECIFIED
}

func (x *InstallToDiskRequest) GetLvmVgName() string {
	if x != nil {
		return x.LvmVgName
	}
	return ""
}

func (x *InstallToDiskRequest) GetLvmLvPrefix() string {
	if x != nil {
		return x.LvmLvPrefix
	}
	return ""
}

func (x *InstallToDiskRequest) GetZfsPoolName() string {
	if x != nil {
		return x.ZfsPoolName
	}
	return ""
}

func (x *InstallToDiskRequest) GetZfsDatasetPrefix() string {
	if x != nil {
		return x.ZfsDatasetPrefix
	}
	return ""
}

func (x *InstallToDiskRequest) GetDisableVxlan() bool {
	if x != nil {
		return x.DisableVxlan
	}
	return false
}

func (x *InstallToDiskRequest) GetSubCaCertPem() string {
	if x != nil {
		return x.SubCaCertPem
	}
	return ""
}

func (x *InstallToDiskRequest) GetSubCaKeyPem() string {
	if x != nil {
		return x.SubCaKeyPem
	}
	return ""
}

func (x *InstallToDiskRequest) GetDcId() string {
	if x != nil {
		return x.DcId
	}
	return ""
}

func (x *InstallToDiskRequest) GetControllers() []string {
	if x != nil {
		return x.Controllers
	}
	return nil
}

func (x *InstallToDiskRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *InstallToDiskRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type InstallToDiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LuksMethod    string                 `protobuf:"bytes,3,opt,name=luks_method,json=luksMethod,proto3" json:"luks_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallToDiskResponse) Reset() {
	*x = InstallToDiskResponse{}
	mi := &file_node_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallToDiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallToDiskResponse) ProtoMessage() {}

func (x *InstallToDiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallToDiskResponse.ProtoReflect.Descriptor instead.
func (*InstallToDiskResponse) Descriptor() ([]byte, []int) {
	return file_node_admin_proto_rawDescGZIP(), []int{1}
}

func (x *InstallToDiskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *InstallToDiskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InstallToDiskResponse) GetLuksMethod() string {
	if x != nil {
		return x.LuksMethod
	}
	return ""
}

var File_node_admin_proto protoreflect.FileDescriptor

const file_node_admin_proto_rawDesc = "" +
	"\n" +
	"\x10node_admin.proto\x12\n" +
	"kcore.node\"\x81\a\n" +
	"\x14InstallToDiskRequest\x12\x17\n" +
	"\aos_disk\x18\x01 \x01(\tR\x06osDisk\x12\x1d\n" +
	"\n" +
	"data_disks\x18\x02 \x03(\tR\tdataDisks\x12\x1e\n" +
	"\n" +
	"controller\x18\x03 \x01(\tR\n" +
	"controller\x12\x1e\n" +
	"\vca_cert_pem\x18\x04 \x01(\tR\tcaCertPem\x12\"\n" +
	"\rnode_cert_pem\x18\x05 \x01(\tR\vnodeCertPem\x12 \n" +
	"\fnode_key_pem\x18\x06 \x01(\tR\n" +
	"nodeKeyPem\x12.\n" +
	"\x13controller_cert_pem\x18\a \x01(\tR\x11controllerCertPem\x12,\n" +
	"\x12controller_key_pem\x18\b \x01(\tR\x10controllerKeyPem\x12\"\n" +
	"\rkctl_cert_pem\x18\t \x01(\tR\vkctlCertPem\x12 \n" +
	"\fkctl_key_pem\x18\n" +
	" \x01(\tR\n" +
	"kctlKeyPem\x12%\n" +
	"\x0erun_controller\x18\v \x01(\bR\rrunController\x12$\n" +
	"\x0edata_disk_mode\x18\f \x01(\tR\fdataDiskMode\x12G\n" +
	"\x0fstorage_backend\x18\r \x01(\x0e2\x1e.kcore.node.StorageBackendTypeR\x0estorageBackend\x12\x1e\n" +
	"\vlvm_vg_name\x18\x0e \x01(\tR\tlvmVgName\x12\"\n" +
	"\rlvm_lv_prefix\x18\x0f \x01(\tR\vlvmLvPrefix\x12\"\n" +
	"\rzfs_pool_name\x18\x10 \x01(\tR\vzfsPoolName\x12,\n" +
	"\x12zfs_dataset_prefix\x18\x11 \x01(\tR\x10zfsDatasetPrefix\x12#\n" +
	"\rdisable_vxlan\x18\x12 \x01(\bR\fdisableVxlan\x12%\n" +
	"\x0fsub_ca_cert_pem\x18\x13 \x01(\tR\fsubCaCertPem\x12#\n" +
	"\x0esub_ca_key_pem\x18\x14 \x01(\tR\vsubCaKeyPem\x12\x13\n" +
	"\x05dc_id\x18\x15 \x01(\tR\x04dcId\x12 \n" +
	"\vcontrollers\x18\x16 \x03(\tR\vcontrollers\x12\x1a\n" +
	"\bhostname\x18\x17 \x01(\tR\bhostname\x12\x17\n" +
	"\anode_id\x18\x18 \x01(\tR\x06nodeId\"n\n" +
	"\x15InstallToDiskResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vluks_method\x18\x03 \x01(\tR\n" +
	"luksMethod*\xba\x01\n" +
	"\x12StorageBackendType\x12$\n" +
	" STORAGE_BACKEND_TYPE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fSTORAGE_BACKEND_TYPE_FILESYSTEM\x10\x01\x12\x1c\n" +
	"\x18STORAGE_BACKEND_TYPE_LVM\x10\x02\x12\x1c\n" +
	"\x18STORAGE_BACKEND_TYPE_ZFS\x10\x03\x12\x1d\n" +
	"\x19STORAGE_BACKEND_TYPE_CEPH\x10\x042a\n" +
	"\tNodeAdmin\x12T\n" +
	"\rInstallToDisk\x12 .kcore.node.InstallToDiskRequest\x1a!.kcore.node.InstallToDiskResponseB>Z<github.com/kcorehypervisor/terraform-provider-kcore/api/nodeb\x06proto3"

var (
	file_node_admin_proto_rawDescOnce sync.Once
	file_node_admin_proto_rawDescData []byte
)

func file_node_admin_proto_rawDescGZIP() []byte {
	file_node_admin_proto_rawDescOnce.Do(func() {
		file_node_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_admin_proto_rawDesc), len(file_node_admin_proto_rawDesc)))
	})
	return file_node_admin_proto_rawDescData
}

var file_node_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_node_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_node_admin_proto_goTypes = []any{
	(StorageBackendType)(0),       // 0: kcore.node.StorageBackendType
	(*InstallToDiskRequest)(nil),  // 1: kcore.node.InstallToDiskRequest
	(*InstallToDiskResponse)(nil), // 2: kcore.node.InstallToDiskResponse
}
var file_node_admin_proto_depIdxs = []int32{
	0, // 0: kcore.node.InstallToDiskRequest.storage_backend:type_name -> kcore.node.StorageBackendType
	1, // 1: kcore.node.NodeAdmin.InstallToDisk:input_type -> kcore.node.InstallToDiskRequest
	2, // 2: kcore.node.NodeAdmin.InstallToDisk:output_type -> kcore.node.InstallToDiskResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_node_admin_proto_init() }
func file_node_admin_proto_init() {
	if File_node_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_admin_proto_rawDesc), len(file_node_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_admin_proto_goTypes,
		DependencyIndexes: file_node_admin_proto_depIdxs,
		EnumInfos:         file_node_admin_proto_enumTypes,
		MessageInfos:      file_node_admin_proto_msgTypes,
	}.Build()
	File_node_admin_proto = out.File
	file_node_admin_proto_goTypes = nil
	file_node_admin_proto_depIdxs = nil
}
