// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: node_admin.proto

package node

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeAdmin_InstallToDisk_FullMethodName = "/kcore.node.NodeAdmin/InstallToDisk"
)

// NodeAdminClient is the client API for NodeAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeAdminClient interface {
	InstallToDisk(ctx context.Context, in *InstallToDiskRequest, opts ...grpc.CallOption) (*InstallToDiskResponse, error)
}

type nodeAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeAdminClient(cc grpc.ClientConnInterface) NodeAdminClient {
	return &nodeAdminClient{cc}
}

func (c *nodeAdminClient) InstallToDisk(ctx context.Context, in *InstallToDiskRequest, opts ...grpc.CallOption) (*InstallToDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallToDiskResponse)
	err := c.cc.Invoke(ctx, NodeAdmin_InstallToDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeAdminServer is the server API for NodeAdmin service.
// All implementations must embed UnimplementedNodeAdminServer
// for forward compatibility.
type NodeAdminServer interface {
	InstallToDisk(context.Context, *InstallToDiskRequest) (*InstallToDiskResponse, error)
	mustEmbedUnimplementedNodeAdminServer()
}

// UnimplementedNodeAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeAdminServer struct{}

func (UnimplementedNodeAdminServer) InstallToDisk(context.Context, *InstallToDiskRequest) (*InstallToDiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallToDisk not implemented")
}
func (UnimplementedNodeAdminServer) mustEmbedUnimplementedNodeAdminServer() {}
func (UnimplementedNodeAdminServer) testEmbeddedByValue()                   {}

// UnsafeNodeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeAdminServer will
// result in compilation errors.
type UnsafeNodeAdminServer interface {
	mustEmbedUnimplementedNodeAdminServer()
}

func RegisterNodeAdminServer(s grpc.ServiceRegistrar, srv NodeAdminServer) {
	// If the following call panics, it indicates UnimplementedNodeAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeAdmin_ServiceDesc, srv)
}

func _NodeAdmin_InstallToDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallToDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAdminServer).InstallToDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAdmin_InstallToDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAdminServer).InstallToDisk(ctx, req.(*InstallToDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeAdmin_ServiceDesc is the grpc.ServiceDesc for NodeAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kcore.node.NodeAdmin",
	HandlerType: (*NodeAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstallToDisk",
			Handler:    _NodeAdmin_InstallToDisk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node_admin.proto",
}
